name: campe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.1
  freezed_annotation: ^0.14.3
  flutter_state_notifier: ^0.7.1
  pedantic_mono: ^1.17.0
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.4
  introduction_screen: ^2.1.0
  font_awesome_flutter: ^9.1.0
  flutter_native_splash: ^1.3.1
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  package_info_plus: ^1.3.0
  flutter_launcher_icons: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  build_runner: ^2.1.2
  json_serializable: ^6.1.3


flutter:
  assets:
    - assets/

  uses-material-design: true