name: campe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  flutter_state_notifier: ^0.7.1
  pedantic_mono: ^1.17.0
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  cloud_firestore: ^3.1.8
  introduction_screen: ^3.0.0
  font_awesome_flutter: ^9.2.0
  flutter_native_splash: ^2.0.5
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  package_info_plus: ^1.4.0
  flutter_launcher_icons: ^0.9.2
  firebase_analytics: ^9.1.2
  device_preview: ^1.0.0
  firestore_ref: ^0.13.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.2
  json_serializable: ^6.1.3


  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/campe_icon_remake.png"

